name: build-deploy-release
on:
  push:
  release:
    types: [published]
jobs:
  deploy-images:
    runs-on: ubuntu-latest
    env:
      registry: ghcr.io
      username: ${{ github.actor }}
      repository: ${{ github.repository }}
      
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: create latest tag variable
        run: |
          container="${{ env.registry }}/${{ env.repository }}:latest"
          echo "container=${container}" >> $GITHUB_ENV
      - name: create release tag variable
        if: github.event_name == 'release'
        run: |
          versioned="${{ env.registry }}/${{ env.repository }}:${GITHUB_REF##*/}"
          echo "versioned=${versioned}" >> $GITHUB_ENV
      - name: build container
        run: |
          docker build -t ${{ env.container }} .

      - name: login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: deploy release (and latest) container
        run: |
          docker tag ${{ env.container }} ${{ env.versioned }}
          docker push ${{ env.versioned }}
          docker push ${{ env.container }}
