
name: Run checks after pull request or commit on [main]
on: 
  workflow_run:
    workflows: [Build and publish Docker image]
    types:
      - completed
jobs:
  r-cmd-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
        fail-fast: false
        matrix:
            config:
                - {os: macos-13,   r: 'release'}
                - {os: ubuntu-latest, r: 'devel'}
                # - {os: windows-2022, r: 'release'}
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
            r-version: ${{ matrix.config.r }}
      - uses: r-lib/actions/setup-pandoc@v2
        with:
            r-version: ${{ matrix.config.r }}

      - name: Setup Docker
        if: runner.os != 'Windows'
        uses: docker/setup-docker-action@v4
      - name: Check Docker version
        if: runner.os != 'Windows'
        run: |
          set -x
          docker version

      - name: Check Docker version if OS is Windows
        if: runner.os == 'Windows'
        run: |
              docker version 
              docker run hello-world
              docker pull ghcr.io/pcgcid/geocoder_pcgc:alpha
              where.exe docker
      - name: Install rmarkdown
        run: Rscript -e 'install.packages("rmarkdown")'
      - name: Install tidyverse
        run: Rscript -e 'install.packages("tidyverse")'      
      - name: Install dplyr
        run: Rscript -e 'install.packages("dplyr")' 
      - name: Install kableExtra
        run: Rscript -e 'install.packages("kableExtra")' 
      - name: Install testthat
        run: Rscript -e 'install.packages("testthat")'  
      - name: Run testthat
        run: Rscript -e 'testthat::test_file(paste0(getwd(),"/tests/testthat/test_docker.R"))'  
    
